//
//  DataService.swift
//  ShoeShock
//
//  Created by ioannis giannakidis on 30/8/21.
//

import Foundation
class DataService {
   
    static let instance = DataService()
     let NikeShoes = [
        Product(brand: "Nike", model: "Zoom Freak", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 130, imageName: "nikezoomfreak"),
        Product(brand: "Nike", model: "Phoenix Air", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 155, imageName: "nikeairforcePhoenix"),
        Product(brand: "Nike", model: "Blazer", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 164, imageName: "nikeblazer"),
        Product(brand: "Nike", model: "Lebron", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 189, imageName: "nikelebron"),
        Product(brand: "Nike", model: "Air Jordan", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 129, imageName: "nikeairjordan")]
    
    let AdidasShoes = [
       Product(brand: "Adidas", model: "Glibe boost", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 135, imageName: "adidasglideboost"),
       Product(brand: "Adidas", model: "Pw", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 155, imageName: "adidaspw"),
       Product(brand: "Adidas", model: "Spring Blade", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 133, imageName: "adidasspringblade"),
       Product(brand: "Adidas", model: "SuperStar", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 128, imageName: "adidassuperstar"),
       Product(brand: "Adidas", model: "Ultra Boost", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 129, imageName: "adidasultraboost")]

    let PumaShoes = [
       Product(brand: "Puma", model: "Marvel Venom", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 167, imageName: "pumamarvelvenom"),
       Product(brand: "Puma", model: "Prevail Og", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 124, imageName: "PumaPrevailOg"),
       Product(brand: "Puma", model: "Roma Cdg", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 213, imageName: "pumaromacdg"),
       Product(brand: "Puma", model: "Aspectra Black", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 128, imageName: "pumaspectrablack"),
       Product(brand: "Puma", model: "Tsugi Shinsei", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 129, imageName: "pumatsugishinsei")]
    

let UnderArmourShoes = [
   Product(brand: "Under Armour", model: "Sc 2", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 167, imageName: "underarmour5"),
   Product(brand: "Under Armour", model: "Sc", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 124, imageName: "underarmour"),
   Product(brand: "Under Armour", model: "Hovr", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 213, imageName: "underarmour2"),
   Product(brand: "Under Armour", model: "Bandit 2", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 128, imageName:  "underarmour3"),
   Product(brand: "Under Armour", model: "Charged", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et risus non nisi venenatis imperdiet. Cras facilisis sem sit amet nulla scelerisque, sit amet volutpat mi tempor. Aliquam tempus varius convallis. Etiam interdum mi sed lacus iaculis, vitae luctus ligula condimentum. Maecenas varius, justo a vulputate blandit, nulla magna eleifend mi, sit amet dictum ligula metus quis turpis. Phasellus vehicula nulla sed dui finibus dignissim. Fusce rutrum pulvinar eros, ac fringilla sem finibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. In aliquam nunc nec augue ornare faucibus. Donec eget risus mi. Nulla lorem sapien, condimentum in tristique at, pharetra eu nibh.", price: 129, imageName: "underarmour4")]

}
